version: '3.8'

services:
  fastapi:
    image: mytherapycoding/fastapi-webserver:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1235:1235"
    volumes:
      - ./static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
